name: Build
on:
    - push

jobs:
  build-macos-arm64:
    name: Build (macOS M1)
    runs-on: [self-hosted, macOS, ARM64]
    defaults:
      run:
        shell: "/usr/bin/arch -arch arm64e /bin/bash {0}"
    steps:
        - name: Status
          run: |
            clang --version
            uname -a
        - name: Checkout
          uses: actions/checkout@v2
        - name: Bundle
          run: bundle install --path vendor/bundle
        - name: Set metadata
          id: set-metadata
          run: |
              bundle exec ruby -e 'puts RUBY_PLATFORM' | tee ruby_platform
              echo "::set-output name=RUBY_PLATFORM::$(cat ruby_platform)"
              bundle exec ruby -e 'puts Gem.platforms.last.to_s' | tee gem_platform
              echo "::set-output name=GEM_PLATFORM::$(cat gem_platform)"
              bundle exec ruby -e 'puts Libv8::Node::VERSION' | tee gem_version
              echo "::set-output name=GEM_VERSION::$(cat gem_version)"
              bundle exec ruby -e 'puts Libv8::Node::NODE_VERSION' | tee node_version
              echo "::set-output name=NODE_VERSION::$(cat node_version)"
              bundle exec ruby -e 'puts Libv8::Node::LIBV8_VERSION' | tee libv8_version
              echo "::set-output name=LIBV8_VERSION::$(cat libv8_version)"
